/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Kamilala
 */
public class FachadaI extends javax.swing.JDialog {

    /**
     * Creates new form FachadaI
     */
    public FachadaI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        productosMenu = new javax.swing.JMenu();
        agregarPrMenu = new javax.swing.JMenuItem();
        actualizarPrMenu = new javax.swing.JMenuItem();
        eliminarPrMenu = new javax.swing.JMenuItem();
        MovimientosMenu = new javax.swing.JMenu();
        compraMenu = new javax.swing.JMenuItem();
        ventaMenu = new javax.swing.JMenuItem();
        inventarioMenu = new javax.swing.JMenu();
        eliminarInventario = new javax.swing.JMenuItem();
        actualizarInventario = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        productoConsulta = new javax.swing.JMenu();
        porClaveConsulta = new javax.swing.JMenuItem();
        porTipoUnidad = new javax.swing.JMenuItem();
        inventarioConsulta = new javax.swing.JMenu();
        todoProductos = new javax.swing.JMenuItem();
        registroVentasMenu = new javax.swing.JMenuItem();
        registroComprasMenu = new javax.swing.JMenuItem();
        ventasPeriodoMenu = new javax.swing.JMenuItem();
        comprasPeriodoMenu = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario Fachada");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Bienvenidos!!");

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Fachada de Abarrotes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        productosMenu.setText("Productos");

        agregarPrMenu.setText("Agregar");
        agregarPrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPrMenuActionPerformed(evt);
            }
        });
        productosMenu.add(agregarPrMenu);

        actualizarPrMenu.setText("Actualizar");
        actualizarPrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPrMenuActionPerformed(evt);
            }
        });
        productosMenu.add(actualizarPrMenu);

        eliminarPrMenu.setText("Eliminar");
        eliminarPrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPrMenuActionPerformed(evt);
            }
        });
        productosMenu.add(eliminarPrMenu);

        jMenuBar1.add(productosMenu);

        MovimientosMenu.setText("Movimientos");

        compraMenu.setText("Compra");
        compraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraMenuActionPerformed(evt);
            }
        });
        MovimientosMenu.add(compraMenu);

        ventaMenu.setText("Venta");
        ventaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaMenuActionPerformed(evt);
            }
        });
        MovimientosMenu.add(ventaMenu);

        inventarioMenu.setText("Inventario");

        eliminarInventario.setText("Eliminar");
        inventarioMenu.add(eliminarInventario);

        actualizarInventario.setText("Actualizar");
        inventarioMenu.add(actualizarInventario);

        MovimientosMenu.add(inventarioMenu);

        jMenuBar1.add(MovimientosMenu);

        consultasMenu.setText("Consultas");

        productoConsulta.setText("Producto");

        porClaveConsulta.setText("Por Clave");
        productoConsulta.add(porClaveConsulta);

        porTipoUnidad.setText("Por Tipo Unidad");
        productoConsulta.add(porTipoUnidad);

        consultasMenu.add(productoConsulta);

        inventarioConsulta.setText("Inventario");

        todoProductos.setText("Todos los productos");
        inventarioConsulta.add(todoProductos);

        registroVentasMenu.setText("Registro de ventas");
        inventarioConsulta.add(registroVentasMenu);

        registroComprasMenu.setText("Registro de compras");
        inventarioConsulta.add(registroComprasMenu);

        ventasPeriodoMenu.setText("Ventas dentro de un periodo dado");
        inventarioConsulta.add(ventasPeriodoMenu);

        comprasPeriodoMenu.setText("Compras dentro de un periodo dado");
        inventarioConsulta.add(comprasPeriodoMenu);

        consultasMenu.add(inventarioConsulta);

        jMenuBar1.add(consultasMenu);

        salir.setText("Salir");
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaMenuActionPerformed
        this.setVisible(false);
        MostrarMenu6 productoMenu = new MostrarMenu6(this, true);
        productoMenu.setLocationRelativeTo(this);
        productoMenu.setVisible(true);
    }//GEN-LAST:event_ventaMenuActionPerformed

    private void compraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraMenuActionPerformed
        this.setVisible(false);
        MostrarMenu5 agregarP = new MostrarMenu5(this, true);
        agregarP.setLocationRelativeTo(this);
        agregarP.setVisible(true);
    }//GEN-LAST:event_compraMenuActionPerformed

    private void agregarPrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPrMenuActionPerformed
        this.setVisible(false);
        AgregarProducto agregarP = new AgregarProducto(this, true);
        agregarP.setLocationRelativeTo(this);
        agregarP.setVisible(true);
    }//GEN-LAST:event_agregarPrMenuActionPerformed

    private void actualizarPrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPrMenuActionPerformed
        this.setVisible(false);
        ActualizarProducto actualizarP = new ActualizarProducto(this, true);
        actualizarP.setLocationRelativeTo(this);
        actualizarP.setVisible(true);
    }//GEN-LAST:event_actualizarPrMenuActionPerformed

    private void eliminarPrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPrMenuActionPerformed
       this.setVisible(false);
        EliminarProducto eliminarP = new EliminarProducto(this, true);
        eliminarP.setLocationRelativeTo(this);
        eliminarP.setVisible(true); 
    }//GEN-LAST:event_eliminarPrMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FachadaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FachadaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FachadaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FachadaI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FachadaI dialog = new FachadaI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MovimientosMenu;
    private javax.swing.JMenuItem actualizarInventario;
    private javax.swing.JMenuItem actualizarPrMenu;
    private javax.swing.JMenuItem agregarPrMenu;
    private javax.swing.JMenuItem compraMenu;
    private javax.swing.JMenuItem comprasPeriodoMenu;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenuItem eliminarInventario;
    private javax.swing.JMenuItem eliminarPrMenu;
    private javax.swing.JMenu inventarioConsulta;
    private javax.swing.JMenu inventarioMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem porClaveConsulta;
    private javax.swing.JMenuItem porTipoUnidad;
    private javax.swing.JMenu productoConsulta;
    private javax.swing.JMenu productosMenu;
    private javax.swing.JMenuItem registroComprasMenu;
    private javax.swing.JMenuItem registroVentasMenu;
    private javax.swing.JMenu salir;
    private javax.swing.JMenuItem todoProductos;
    private javax.swing.JMenuItem ventaMenu;
    private javax.swing.JMenuItem ventasPeriodoMenu;
    // End of variables declaration//GEN-END:variables
}
